const CartTypes = {
    TOOGLE_CART_HIDDEN: "TOOGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    REMOVE_ITEM: "REMOE_VITEM",
    CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART ",
};

export default CartTypes;
